

networks:
  employeeapp:
    driver: bridge

services:
  employeecrud.api:
    container_name: employee-management-system
    build:
      context: .
      dockerfile: employeecrud.api/Dockerfile
    image: ${docker_registry-}employeecrudapi
    ports:
      - 8080:8080
      - 8081:8081
    # ports:
    #     - "5001:5224"
    # environment:
    #   - db_host=host.docker.internal
    #   - db_user=sa
    #   - db_sa_password=password@12345#
    # networks:
    #   - employeeapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - employeeapp
    volumes:
      - ./data-protection:/root/.aspnet/DataProtection-Keys





