CREATE or ALTER PROCEDURE DeleteEmployee
	@Id UNIQUEIDENTIFIER

	As
	BEGIN
		SET NOCOUNT ON;
		DECLARE @UserId UNIQUEIDENTIFIER;
		SELECT @UserId= Id FROM AspNetUsers Where EmployeeId=@Id;
		DELETE FROM AspNetUserRoles WHERE UserId = @UserId;
		DELETE FROM AspNetUsers WHERE Id=@UserId;
		DELETE FROM Employees WHERE Id = @Id;
	END